#!/bin/bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero Public License for more details.
#
# You should have received a copy of the GNU Affero Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------

# Update MOTD if updates are available for HTM-IT. Warn them about not running
# yum or salt either way.

UPDATES_ARE_AVAILABLE_F=/tmp/htm-it-update-available

fmt << END_WARNING

Do not manually run yum update or salt! You are very likely to break your
HTM-IT instance.

Never manually update the installed version of salt, the HTM-IT formulas are
only tested with the version of SaltStack bundled with the HTM-IT instance.

END_WARNING

if [ -f "${UPDATES_ARE_AVAILABLE_F}" ]; then
fmt << END_UPDATE_MESSAGE

HTM-IT updates are available. To install the updates, please use the web
interface.

Manually running salt or yum update will almost certainly break your HTM-IT
instance.

END_UPDATE_MESSAGE
fi
