#!/bin/bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero Public License for more details.
#
# You should have received a copy of the GNU Affero Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------

# Display the version of HTM-IT in /etc/motd

if [ -d /opt/numenta/htm.it/conf ]; then
  export PYTHONPATH="${PYTHONPATH}:/opt/numenta/htm.it"

  HTM_IT_VERSION=$(python -c "import htm.it;print htm.it.__version__")
  HTM_IT_ID=$(python -c "from htm.it.app import config; print config.get('usertrack', 'htm_it_id')")

  echo "HTM-IT version: ${HTM_IT_VERSION}"
  echo "HTMITID: ${HTM_IT_ID}"
else
  echo "HTM-IT is not installed on this machine."
fi
