#!/bin/bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero Public License for more details.
#
# You should have received a copy of the GNU Affero Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------

# Display the version of the htm-it rpms installed on this machine.

# HTM-IT data
if [ -f /etc/htm.it/build.time ]; then
  htm_it_ami_build_time=$(cat /etc/htm.it/build.time)
  echo "HTM-IT AMI Build time: ${htm_it_ami_build_time}"
fi
echo

# HTM-IT was originally code-named "Mercury". There are still legacy artifacts
# on some older servers that include mercury in the package name, so we want to
# continue to search for them.  If we see any "Mercury" packages, we should work
# to remove them so we can drop the `-e mercury` search from this list.
echo "Currently installed HTM-IT rpms:"
for rpm in $(rpm -qa | grep -e nupic -e htm-it -e saltcellar -e mercury | sort)
do
  echo "  ${rpm}"
done

CENTOS_SHA_F=/etc/htm.it/centos/operations-scripts.sha
HTM_IT_SHA_F=/opt/numenta/products/htm-it/static/htm-it.sha
NUPIC_SHA_F=/opt/numenta/nupic/nupic.build.sa

echo
echo "Installed SHAs:"

if [ -f "${CENTOS_SHA_F}" ]; then
  echo " centos: $(cat ${CENTOS_SHA_F})"
fi

if [ -f "${HTM_IT_SHA_F}" ]; then
  echo "   htm-it: $(cat ${HTM_IT_SHA_F})"
fi

if [ -f "${NUPIC_SHA_F}" ]; then
  echo "  nupic: $(cat ${NUPIC_SHA_F})"
fi
