"""sans xignite security news

Revision ID: 375d9de88cfd
Revises: 12c41f6f39a
Create Date: 2015-12-28 16:14:17.667090

"""

# revision identifiers, used by Alembic.
revision = '375d9de88cfd'
down_revision = '12c41f6f39a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic ###
    op.drop_table('xignite_security_headline')
    op.drop_table('xignite_security_release')
    ### end Alembic commands ###


def downgrade():
    raise NotImplementedError("Rollback is not supported.")
