#!/usr/bin/env bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------

# This script bakes an AMI. Accepts tracking RPM name and and AMI name

set -o errexit
set -o pipefail

export PATH="/opt/numenta/packer:${PATH}"

# This is required by aws-cli
export AWS_DEFAULT_REGION="us-west-2"

reporoot=$(git rev-parse --show-toplevel)
amidir="${reporoot}/infrastructure/ami-tools"

scratch_f=$(mktemp /tmp/packer-output.XXXXXX)

# Exported so packer can read it
export GROK_INSTALL_MANIFEST=$(mktemp /tmp/grok-manifest.XXXXXX)

cleanUp() {
  echo "Cleaning up ${scratch_f} and ${GROK_INSTALL_MANIFEST}"
  if [ -z "${KEEPFILES}" ]; then
    rm -rfv "${scratch_f}" "${GROK_INSTALL_MANIFEST}"
  fi
}

trap cleanUp SIGQUIT SIGKILL SIGTERM

makeManifest() {
  "${amidir}"/create-grok-manifest --manifest-file "${GROK_INSTALL_MANIFEST}" \
    --install-package "${GROK_RPM_NAME}" \
    --description "Grok Manifest, Build ${BUILD_NUMBER}" \
    --log-level warning
  if [ -n "${DEBUG}" ]; then
    echo "Manifest:"
    cat "${GROK_INSTALL_MANIFEST}"
    echo
  fi
}

# TODO TAUR-824 use "aws ec2 describe-images" to retrieve AMI Id
real_ami_bake() {
  pushd "${amidir}"
  git status
  echo "This will take a while..."

  scratch_f=$(mktemp /tmp/packer-output.XXXXXX)
  rake bake_grok_pipeline | tee "${scratch_f}"
  packer_output=$(cat ${scratch_f})
  trimmed=${packer_output##*us-west-2:}
  rm -f "${scratch_f}"
  ami_id=`echo ${trimmed}| cut -d' ' -f1`
  echo "Created AMI: ${ami_id}"
  popd
  echo "AMI_ID: ${ami_id}" > ami.txt
}

if [[ -z "$1"  || -z "$2" ]]; then
  echo "USAGE: $0 <grok_rpm_version> <ami_name>"
  echo "EXAMPLE: bake_ami nta-products-grok-1.7.0-9198.noarch.rpm numenta-master"
  exit 1
fi

# TODO TAUR-1117 Update to use infrastructure.utilities.jenkins.getBuildNumber()
if [ -z "${BUILD_NUMBER}" ]; then
  BUILD_NUMBER=`git log -n1 --pretty=%H`
  if [ -z "${BUILD_NUMBER}" ]; then
    echo "You must run this from within a Grok repository or set BUILD_NUMBER"
    exit 1
  fi
fi

export GROK_RPM_NAME="$1"
export AMI_NAME="$2"

makeManifest
real_ami_bake
cleanUp
