#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/

# Set the permissions & ownership for anaconda
#
# Some roles (like the jenkins infrastructure) need write permission in
# /opt/numenta/anaconda for users other than ec2-user.

ANACONDA_D="/opt/numenta/anaconda"
ANACONDA_OWNER_F="/etc/numenta/anaconda-owner"

# Check to see what user should own the anaconda tree
if [ -f "${ANACONDA_OWNER_F}" ]; then
  ANACONDA_OWNER=$(cat "${ANACONDA_OWNER_F}")
else
  ANACONDA_OWNER="ec2-user:engineering"
fi

# Fixup the permissions in the anaconda tree
chown -R "${ANACONDA_OWNER}" "${ANACONDA_D}"

# Grant write permission to group on directories
find "${ANACONDA_D}" -type d -exec chmod g+rwx '{}' ';'

# And files
find "${ANACONDA_D}" -type f -exec chmod g+rw '{}' ';'
