source 'https://github.com/CocoaPods/Specs.git'

pod 'FMDB'
#pod 'MMDrawerController', '~> 0.5.7'
pod'AWSCore'
#pod 'AWSAutoScaling'
#pod 'AWSCloudWatch'
pod 'AWSDynamoDB'
#pod 'AWSEC2'
#pod 'AWSElasticLoadBalancing'
#pod 'AWSKinesis'
#pod 'AWSLambda'
#pod 'AWSMachineLearning'
#pod 'AWSMobileAnalytics'
#pod 'AWSS3'
#pod 'AWSSES'
#pod 'AWSSimpleDB'
#pod 'AWSSNS'
#pod 'AWSSQS'
pod 'AWSCognito'



xcodeproj 'taurus.xcodeproj'

