#!/usr/bin/env python
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero Public License for more details.
#
# You should have received a copy of the GNU Affero Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------

"""
  NuPIC pipeline script
"""

"""
Workflow of the NuPIC pipeline.

For each commit to NuPIC
  - read NUPIC_CORE_SHA from .nupic_modules
  - check (local_cache) if NUPIC_CORE_SHA has been built previously
    - if YES
      - set NUPIC_CORE_PATH to /var/build/nupic.core/NUPIC_CORE_SHA
    - if NO
      - fetch nupic.core
      - build nupic.core
      - copy the build to /var/build/nupic.core/NUPIC_CORE_SHA
      - set NUPIC_CORE_PATH to /var/build/nupic.core/NUPIC_CORE_SHA
  - build NuPIC, provide /var/build/nupic.core/NUPIC_CORE_SHA as NUPIC_CORE_PATH
    to CMAKE_OPTIONS
  - test NuPIC
    - if tests pass,
      - cache NuPIC to /var/build/nupic/SHA
      - package NuPIC
      - notify
    - if tests fail
      - notify
"""

import argparse
import os

from pkg_resources import resource_stream

import yaml

from infrastructure.utilities import git
from infrastructure.utilities import jenkins
from infrastructure.utilities import diagnostics
from infrastructure.utilities.env import prepareEnv
from infrastructure.utilities.nupic.build_commands import (
  checkIfProjectExistsLocallyForSHA,
  executeBuildProcess)
from infrastructure.utilities.path import mkdirp

g_config = yaml.load(resource_stream(__name__,
                                     "../../../conf/nupic/config.yaml"))
g_logger = None


def addAndParseArgs():
  """
    Parse the command line arguments

    :returns: A dict of parsed command line arguments
    :rtype: dict
  """
  parser = argparse.ArgumentParser(description=("Build tool for NuPIC. To "
                                                "create a release version, set "
                                                "both --nupic-branch and "
                                                "--nupic-sha to a git release "
                                                "tag (e.g., 0.2.3) that already"
                                                " exists in NuPIC."))
  parser.add_argument("--build-workspace",
                      dest="buildWorkspace",
                      type=str,
                      default=os.environ.get("BUILD_WORKSPACE"),
                      help="Common build directory for NuPIC, "
                           "overrides $BUILD_WORKSPACE env var if set.")
  parser.add_argument("--nupic-remote",
                      dest="nupicRemote",
                      type=str,
                      default="git@github.com:numenta/nupic.git",
                      help="Which NuPIC remote to build from, e.g., "
                           "git@github.com:numenta/nupic.git")
  parser.add_argument("--nupic-branch",
                      dest="nupicBranch",
                      type=str,
                      default="master",
                      help="The NuPIC branch to add in deploy track")
  parser.add_argument("--sha",
                      dest="nupicSha",
                      type=str,
                      help="The NuPIC SHA that needs to be built.")
  parser.add_argument("--nupic-core-remote",
                      dest="nupicCoreRemote",
                      type=str,
                      default="",
                      help="Which NuPIC Core remote to build from, e.g., "
                           "git@github.com:numenta/nupic.core.git")
  parser.add_argument("--sha-core",
                      dest="nupicCoreSha",
                      type=str,
                      default="None",
                      help="The NuPIC Core SHA that needs to be built.")
  parser.add_argument("--log",
                      dest="logLevel",
                      type=str,
                      default="warning",
                      choices=diagnostics.LOG_LEVELS,
                      help="Logging level, by default it takes warning")

  args = vars(parser.parse_args())

  global g_logger # pylint: disable=W0603
  g_logger = diagnostics.initPipelineLogger(name="build",
                                            logLevel=args["logLevel"])

  if not args["buildWorkspace"]:
    args["buildWorkspace"] = jenkins.defineBuildWorkspace(logger)
    mkdirp(args["buildWorkspace"])
    g_logger.warning("You did not specify a Build Workspace via the command "
                     "line or via a BUILD_WORKSPACE env var, so one was "
                     "created for you at %s.", args["buildWorkspace"])

  return args



def main():
  """
    Entry point to run the nupic pipeline

  """
  args = addAndParseArgs()

  env = prepareEnv(args["buildWorkspace"], None, os.environ)
  installDir = os.path.join(args["buildWorkspace"],
                            "lib/python2.7/site-packages/")
  scriptDir = os.path.join(args["buildWorkspace"], "bin")
  mkdirp(path=installDir)
  mkdirp(path=scriptDir)

  env.update(PYTHONPATH=installDir)
  env.update(PATH="%s:%s" % (scriptDir, os.environ.get("PATH")))
  diagnostics.printEnv(env=env, logger=g_logger)

  if not args["nupicSha"]:
    args["nupicSha"] = \
      git.getShaFromRemoteBranch(gitRemoteRepo=args["nupicRemote"],
                                 gitRemoteBranch=args["nupicBranch"],
                                 logger=g_logger)

  if not checkIfProjectExistsLocallyForSHA("nupic", args["nupicSha"], g_logger):
    executeBuildProcess(env=env,
                        buildWorkspace=args["buildWorkspace"],
                        nupicRemote=args["nupicRemote"],
                        nupicBranch=args["nupicBranch"],
                        nupicSha=args["nupicSha"],
                        nupicCoreRemote=args["nupicCoreRemote"],
                        nupicCoreSha=args["nupicCoreSha"],
                        logger=g_logger)
  else:
    g_logger.info("Skipping NuPIC build for SHA : %s", args["nupicSha"])



if __name__ == "__main__":
  main()
