#!/usr/bin/env bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------


# ----------------------------------------------------------------------
#
# README
#
# ----------------------------------------------------------------------
# This is a convenience script to install Grok onto a bare Centos 7 machine.
# 
# It was tested against a Centos 7 instance in AWS on 9 July 2015:
#   AWS Marketplace: https://aws.amazon.com/marketplace/pp/B00O7WM7QW
#   AMI ID: ami-c7d092f7 in us-west-2
#
# To run this:
#
# 1. Launch a Centos 7 AMI or VM
# 2. scp /path/to/install-grok-from-bare-centos7.sh centos@<server_ip>:~
# 3. ssh centos@<server_ip>
# 4. chmod +x install-grok-from-bare-centos7.sh
# 5. ./install-grok-from-bare-centos7.sh
#
# ----------------------------------------------------------------------

set -o errexit
set -o pipefail

NUMENTA=/opt/numenta
PRODUCTS="${NUMENTA}/numenta-apps"
GROK_HOME="${PRODUCTS}/grok"

splat() {
  # Make it easier to distinguish phases of the script in the scrollback
  echo "


.                                    ######
.                                  ##########
.                                 ############
.                                ##############
.                                ##############
.                                ##############
.                                 ############
.                                  ##########
.                                    ######


  "
}

install-prerequisites-and-update-repos() {
  splat

  echo "Installing devtools, mysql, and rabbit"
  # Install base centos packages
  sudo yum install gcc gcc-c++ -y
  sudo rpm -iUvh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
  sudo yum -y install python-pip python-devel libxml2-devel libxslt-devel

  # Install MySQL and Rabbit
  sudo rpm -Uvh http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm
  sudo yum install mysql-server mysql mariadb-devel rabbitmq-server nginx git -y
  sudo /usr/lib/rabbitmq/bin/rabbitmq-plugins enable rabbitmq_management

  # Create /opt/numenta folder
  sudo mkdir -p "${NUMENTA}"
  sudo mkdir -p /etc/grok
  sudo chown -R centos:centos "${NUMENTA}"
  sudo chown -R centos:centos /etc/grok
}

install-grok() {
  splat

  echo "Installing Grok"

  # Install Grok pre-requisites
  pip install paver==1.2.4 uwsgi==2.0.4 agamotto==0.5.1 --user

  # Clone Numenta Apps Repo
  git clone https://github.com/numenta/numenta-apps.git "${PRODUCTS}"

  echo "Creating symlink to ${NUMENTA}/grok"
  ln -s "${GROK_HOME}" "${NUMENTA}/grok"

  echo "Creating symlink for supervisord.vars"
  ln -s "${PRODUCTS}/grok/supervisord.vars" /etc/grok/
  echo "Sourcing supervisord.vars..."
  source /etc/grok/supervisord.vars

  BOOTSCRIPTS_D="${PRODUCTS}/infrastructure/ami-tools/boot-scripts"
  echo "Creating symlink for firstboot.sh"
  ln -s "${BOOTSCRIPTS_D}/firstboot.sh" /usr/local/sbin/

  echo "Creating symlink for firstboot-root.sh"
  ln -s "${BOOTSCRIPTS_D}/firstboot-root.sh" /usr/local/sbin/

  echo "Creating symlink for grokservices init script"
  ln -s "${BOOTSCRIPTS_D}/grokservices" /etc/init.d/

  echo "Creating symlink for set-mysql-root-password"
  ln -s "${BOOTSCRIPTS_D}/set-mysql-root-password" /usr/local/sbin/

  echo "Creating symlink for set-rabbitmq-root-password"
  ln -s "${BOOTSCRIPTS_D}/set-rabbitmq-root-password" /usr/local/sbin/

  echo "Creating symlink for supervisord-helper"
  ln -s "${BOOTSCRIPTS_D}/supervisord-helper" "${NUMENTA}"

  cd "${PRODUCTS}"
  ./install-grok.sh /home/centos/.local/lib/python2.7/site-packages /home/centos/.local/bin
}

start-3rd-party-services() {
  splat

  echo "Starting MySQL and Rabbit"
  # Start MySQL
  sudo service mysqld start

  # Add Rabbit Admin scripts and start Rabbit
  sudo ln -s "${PRODUCTS}/infrastructure/saltcellar/rabbitmq/files/rabbitmqadmin" /usr/local/bin/rabbitmqadmin
  sudo rabbitmq-server -detached
}

bootstrap-and-start-grok() {
  splat

  echo "Bootstrap Grok"
  # Increase max connections for Grok
  sudo sysctl -w net.core.somaxconn=1024

  cd "${GROK_HOME}"
  mkdir -p "${GROK_LOG_DIR}"/

  sudo service grokservices start
}

install-prerequisites-and-update-repos
install-grok
start-3rd-party-services
bootstrap-and-start-grok
