#!/bin/bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero Public License for more details.
#
# You should have received a copy of the GNU Affero Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------

# DO NOT MAKE THIS SCRIPT RUN SALT! It will be run on all AMIs, it should
# never contain specific changes for different AMI builds
#
# It is only to install the tooling and salt binaries. The packer configuration
# calling this will almost certainly need to set some parameters before it
# kicks off a salt run.
#
# If we run salt here, we'll end up having to run it again once the real
# configuration is in place.

bootstrap_salt(){
  echo "Bootstrapping salt..."
  sudo chmod +x /tmp/bootstrap-salt.sh

  if [ -f /tmp/infrastructure_minion_id ]; then
    echo "Setting minion id.."
    cat /tmp/infrastructure_minion_id > /tmp/minion_id
    sudo mv /tmp/minion_id /etc/salt/minion_id
  fi

  sudo /tmp/bootstrap-salt.sh -A salt.numenta.com
}

prep_instance_for_salt(){
  echo "Updating yum cache..."
  sudo yum clean all

  echo "Ensure we have the latest git, wget & curl"
  echo "before installing salt"

  # Do this as one yum command so we only have to wait for yum
  # initialization once
  sudo yum install -y \
    curl \
    git \
    wget

  echo "Installing S3 support for yum..."
  sudo yum install -y /tmp/yum-s3-0.2.4-1.noarch.rpm
}

setup_directories(){
  sudo mkdir -p /etc/salt
  sudo mkdir -p /usr/local/bin
  sudo mkdir -p /usr/local/sbin
}

prep_instance_for_salt
setup_directories
bootstrap_salt
