#!/bin/bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------install-option="--install-dir=lib/python2.7/site-packages" --no-deps"
# regenerates the .pth files so they point to /opt/numenta/grok instead
# of the build paths from the jenkins slaves.

set -o pipefail
set -o errexit

if [ -n "${VERBOSE_DEBUG}" ]; then
  set -o xtrace
fi

cd /opt/numenta/grok

export NUPIC=/opt/numenta/nupic
export NUMENTA=/opt/numenta
export PRODUCTS=/opt/numenta/products

source /etc/grok/supervisord.vars

if [ -n "${VERBOSE_DEBUG}" ]; then
  pwd
  echo "${NUPIC}"
  echo "In grok rpm postinstall script, dumping env"
  env | sort
  echo "end postinstall env dump"
fi

# TODO: TAUR-845 Figure out why psutil and PyYAML are being deleted.

pip install psutil==1.2.1

python setup.py develop --install-dir=lib/python2.7/site-packages --script-dir=bin
