#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (C) 2014 Numenta Inc. All rights reserved.
#
# The information and source code contained herein is the
# exclusive property of Numenta Inc. No part of this software
# may be used, reproduced, stored or distributed in any form,
# without explicit written authorization from Numenta Inc.
#
# This script is executed when a grok RPM is installed using rpm or yum,
# after all the files have been installed.
#
# We’re building the RPMs outside of a Grok instance in an arbitrary tree
# structure, which is what leads to the incorrect .pth / .egg-info files.
#
# This command "pip install -e /opt/numents/grok
# --install-option="--install-dir=lib/python2.7/site-packages" --no-deps"
# regenerates the .pth files so they point to /opt/numenta/grok instead
# of the build paths from the jenkins slaves.

set -o pipefail
set -o errexit

if [ -n "${VERBOSE_DEBUG}" ]; then
  set -o xtrace
fi

cd /opt/numenta/grok

export NUPIC=/opt/numenta/nupic
export NUMENTA=/opt/numenta
export PRODUCTS=/opt/numenta/products

source /etc/grok/supervisord.vars

if [ -n "${VERBOSE_DEBUG}" ]; then
  pwd
  echo "${NUPIC}"
  echo "In grok rpm postinstall script, dumping env"
  env | sort
  echo "end postinstall env dump"
fi

# TODO: TAUR-845 Figure out why psutil and PyYAML are being deleted.

pip install psutil==1.2.1

python setup.py develop --install-dir=lib/python2.7/site-packages --script-dir=bin
