#!/usr/bin/env bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero Public License for more details.
#
# You should have received a copy of the GNU Affero Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------
#
# grok-preload        Non-standard nginx states
#
# chkconfig: - 20 15
# processname: nginx
# config: /etc/nginx/nginx.conf
# config: /etc/sysconfig/nginx
# pidfile: /var/run/nginx.pid
# description: nginx is an HTTP and reverse proxy server
#
### BEGIN INIT INFO
# Provides: nginx
# Required-Start: $local_fs $remote_fs $network
# Required-Stop: $local_fs $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop nginx
### END INIT INFO

if [ $(/usr/bin/id -u) -ne 0 ]; then
    echo "You are not root"
    exit 1
fi

# Source function library.
source /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/nginx ]; then
    source /etc/sysconfig/nginx
fi

# We don't want to use the system nginx.conf - we want to use the
# grok-api.conf installed as part of grok app

source /etc/grok/supervisord.vars

prog=nginx
nginx=/usr/sbin/nginx

# Set up different conf files for the varying states.
error_conf="${GROK_HOME}/conf/nginx-error.conf"
loading_conf="${GROK_HOME}/conf/nginx-loading.conf"
stopped_conf="${GROK_HOME}/conf/nginx-stopped.conf"
standard_conf="${GROK_HOME}/conf/grok-api.conf"

lockfile=${LOCKFILE-/var/lock/subsys/nginx}
pidfile=${PIDFILE-/var/run/nginx.pid}

SLEEPMSEC=100000
RETVAL=0

grok_error() {
  stop
  cd "${GROK_HOME}"
  echo -n $"Setting ${prog} status to grok_error: "
  logger -t grok-preload "Setting ${prog} status to grok_error: "

  daemon --pidfile="${pidfile}" "${nginx}" -c "${error_conf}"
  RETVAL=$?
  echo
  [ "${RETVAL}" = 0 ] && touch "${lockfile}"
  return "${RETVAL}"
}

grok_loading() {
  stop
  cd "${GROK_HOME}"
  echo -n $"Setting ${prog} status to grok_loading: "
  logger -t grok-preload "Setting ${prog} status to grok_loading: "

  daemon --pidfile="${pidfile}" "${nginx}" -c "${loading_conf}"
  RETVAL=$?
  echo
  [ "${RETVAL}" = 0 ] && touch "${lockfile}"
  return "${RETVAL}"
}

grok_stopped() {
  stop
  cd "${GROK_HOME}"
  echo -n $"Setting ${prog} status to grok_stopped: "
  logger -t grok-preload "Setting ${prog} status to grok_stopped: "

  daemon --pidfile="${pidfile}" "${nginx}" -c "${stopped_conf}"
  RETVAL=$?
  echo
  [ "${RETVAL}" = 0 ] && touch "${lockfile}"
  return "${RETVAL}"
}

start_grok() {
  echo -n $"Starting ${prog}: "
  logger -t grok-preload "starting: "
  daemon --pidfile="${pidfile}" "${nginx}" -c "${standard_conf}"
  RETVAL=$?
  echo
  [ "${RETVAL}" = 0 ] && touch "${lockfile}"
  return "${RETVAL}"
}

stop() {
    echo -n $"Stopping ${prog}: "
    logger -t grok-preload "stopping: "
    killproc -p "${pidfile}" "${prog}"
    RETVAL=$?
    echo
    [ "${RETVAL}" = 0 ] && rm -f "${lockfile}" "${pidfile}"
}

reload() {
    cd "${GROK_HOME}"
    echo -n $"Reloading ${prog}: "
    logger -t grok-preload "reloading: "
    killproc -p "${pidfile}" "${prog}" -HUP
    RETVAL=$?
    echo
}

configtest() {
    logger -t grok-preload "configtest: "
    nginx -c "${GROK_HOME}/${GROK_NGINX_CONF}" -t
}

rh_status() {
    cd "${GROK_HOME}"
    logger -t grok-preload "rh_status: "
    status -p "${pidfile}" "${nginx}"
}

# See how we were called.
case "$1" in
    start)
        rh_status >/dev/null 2>&1 && exit 0
        grok_loading
        ;;
    stop)
        stop
        ;;
    grok-loading)
        grok_loading
        ;;
    grok-error)
        grok_error
        ;;
    grok-stopped)
        grok_stopped
        ;;
    grok-start)
        start_grok
        ;;
    status)
        rh_status
        RETVAL=$?
        ;;
    restart)
        # configtest -q || exit $RETVAL
        stop
        start
        ;;
    restart-grok)
        # configtest -q || exit $RETVAL
        stop
        start_grok
        ;;
    upgrade)
        upgrade
        ;;
    condrestart|try-restart)
        if rh_status >/dev/null 2>&1; then
            stop
            start
        fi
        ;;
    force-reload|reload)
        reload
        ;;
    configtest)
        configtest
        ;;
    *)
        echo $"Usage: ${prog} {start|stop|grok-error|grok-loading|grok-stopped|restart|condrestart|try-restart|force-reload|upgrade|reload|status|help|configtest}"
        RETVAL=2
esac

exit "${RETVAL}"
